/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEsporteRouteImport } from './routes/_authenticated/esporte'
import { Route as AuthenticatedFaculdadeRouteImport } from './routes/_authenticated/faculdade'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedNosRouteImport } from './routes/_authenticated/nos'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedContextosIndexRouteImport } from './routes/_authenticated/contextos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEsporteRoute = AuthenticatedEsporteRouteImport.update({
  id: '/esporte',
  path: '/esporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaculdadeRoute = AuthenticatedFaculdadeRouteImport.update({
  id: '/faculdade',
  path: '/faculdade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNosRoute = AuthenticatedNosRouteImport.update({
  id: '/nos',
  path: '/nos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContextosIndexRoute =
  AuthenticatedContextosIndexRouteImport.update({
    id: '/contextos/',
    path: '/contextos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/esporte': typeof AuthenticatedEsporteRoute
  '/faculdade': typeof AuthenticatedFaculdadeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/nos': typeof AuthenticatedNosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/contextos/': typeof AuthenticatedContextosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/esporte': typeof AuthenticatedEsporteRoute
  '/faculdade': typeof AuthenticatedFaculdadeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/nos': typeof AuthenticatedNosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/contextos': typeof AuthenticatedContextosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/esporte': typeof AuthenticatedEsporteRoute
  '/_authenticated/faculdade': typeof AuthenticatedFaculdadeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/nos': typeof AuthenticatedNosRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/contextos/': typeof AuthenticatedContextosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/esporte'
    | '/faculdade'
    | '/financeiro'
    | '/metas'
    | '/nos'
    | '/notas'
    | '/tarefas'
    | '/contextos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/esporte'
    | '/faculdade'
    | '/financeiro'
    | '/metas'
    | '/nos'
    | '/notas'
    | '/tarefas'
    | '/contextos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/esporte'
    | '/_authenticated/faculdade'
    | '/_authenticated/financeiro'
    | '/_authenticated/metas'
    | '/_authenticated/nos'
    | '/_authenticated/notas'
    | '/_authenticated/tarefas'
    | '/_authenticated/contextos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/esporte': {
      id: '/_authenticated/esporte'
      path: '/esporte'
      fullPath: '/esporte'
      preLoaderRoute: typeof AuthenticatedEsporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculdade': {
      id: '/_authenticated/faculdade'
      path: '/faculdade'
      fullPath: '/faculdade'
      preLoaderRoute: typeof AuthenticatedFaculdadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nos': {
      id: '/_authenticated/nos'
      path: '/nos'
      fullPath: '/nos'
      preLoaderRoute: typeof AuthenticatedNosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contextos/': {
      id: '/_authenticated/contextos/'
      path: '/contextos'
      fullPath: '/contextos/'
      preLoaderRoute: typeof AuthenticatedContextosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEsporteRoute: typeof AuthenticatedEsporteRoute
  AuthenticatedFaculdadeRoute: typeof AuthenticatedFaculdadeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNosRoute: typeof AuthenticatedNosRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedContextosIndexRoute: typeof AuthenticatedContextosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEsporteRoute: AuthenticatedEsporteRoute,
  AuthenticatedFaculdadeRoute: AuthenticatedFaculdadeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNosRoute: AuthenticatedNosRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedContextosIndexRoute: AuthenticatedContextosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
